version: "3"
services:
  vue-app:
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - node-app
  node-app:
    build: 
      context: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
      - vue-app


volumes:
  mongo-db:
